/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vkc.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Impressions extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4999308310259643863L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Impressions\",\"namespace\":\"com.vkc.avro\",\"fields\":[{\"name\":\"adId\",\"type\":\"string\"},{\"name\":\"impressionTime\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Impressions> ENCODER =
      new BinaryMessageEncoder<Impressions>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Impressions> DECODER =
      new BinaryMessageDecoder<Impressions>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Impressions> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Impressions> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Impressions> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Impressions>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Impressions to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Impressions from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Impressions instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Impressions fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence adId;
  @Deprecated public long impressionTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Impressions() {}

  /**
   * All-args constructor.
   * @param adId The new value for adId
   * @param impressionTime The new value for impressionTime
   */
  public Impressions(java.lang.CharSequence adId, java.lang.Long impressionTime) {
    this.adId = adId;
    this.impressionTime = impressionTime;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return adId;
    case 1: return impressionTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: adId = (java.lang.CharSequence)value$; break;
    case 1: impressionTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'adId' field.
   * @return The value of the 'adId' field.
   */
  public java.lang.CharSequence getAdId() {
    return adId;
  }


  /**
   * Sets the value of the 'adId' field.
   * @param value the value to set.
   */
  public void setAdId(java.lang.CharSequence value) {
    this.adId = value;
  }

  /**
   * Gets the value of the 'impressionTime' field.
   * @return The value of the 'impressionTime' field.
   */
  public long getImpressionTime() {
    return impressionTime;
  }


  /**
   * Sets the value of the 'impressionTime' field.
   * @param value the value to set.
   */
  public void setImpressionTime(long value) {
    this.impressionTime = value;
  }

  /**
   * Creates a new Impressions RecordBuilder.
   * @return A new Impressions RecordBuilder
   */
  public static com.vkc.avro.Impressions.Builder newBuilder() {
    return new com.vkc.avro.Impressions.Builder();
  }

  /**
   * Creates a new Impressions RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Impressions RecordBuilder
   */
  public static com.vkc.avro.Impressions.Builder newBuilder(com.vkc.avro.Impressions.Builder other) {
    if (other == null) {
      return new com.vkc.avro.Impressions.Builder();
    } else {
      return new com.vkc.avro.Impressions.Builder(other);
    }
  }

  /**
   * Creates a new Impressions RecordBuilder by copying an existing Impressions instance.
   * @param other The existing instance to copy.
   * @return A new Impressions RecordBuilder
   */
  public static com.vkc.avro.Impressions.Builder newBuilder(com.vkc.avro.Impressions other) {
    if (other == null) {
      return new com.vkc.avro.Impressions.Builder();
    } else {
      return new com.vkc.avro.Impressions.Builder(other);
    }
  }

  /**
   * RecordBuilder for Impressions instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Impressions>
    implements org.apache.avro.data.RecordBuilder<Impressions> {

    private java.lang.CharSequence adId;
    private long impressionTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vkc.avro.Impressions.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.adId)) {
        this.adId = data().deepCopy(fields()[0].schema(), other.adId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.impressionTime)) {
        this.impressionTime = data().deepCopy(fields()[1].schema(), other.impressionTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Impressions instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vkc.avro.Impressions other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.adId)) {
        this.adId = data().deepCopy(fields()[0].schema(), other.adId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.impressionTime)) {
        this.impressionTime = data().deepCopy(fields()[1].schema(), other.impressionTime);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'adId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdId() {
      return adId;
    }


    /**
      * Sets the value of the 'adId' field.
      * @param value The value of 'adId'.
      * @return This builder.
      */
    public com.vkc.avro.Impressions.Builder setAdId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.adId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'adId' field has been set.
      * @return True if the 'adId' field has been set, false otherwise.
      */
    public boolean hasAdId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'adId' field.
      * @return This builder.
      */
    public com.vkc.avro.Impressions.Builder clearAdId() {
      adId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'impressionTime' field.
      * @return The value.
      */
    public long getImpressionTime() {
      return impressionTime;
    }


    /**
      * Sets the value of the 'impressionTime' field.
      * @param value The value of 'impressionTime'.
      * @return This builder.
      */
    public com.vkc.avro.Impressions.Builder setImpressionTime(long value) {
      validate(fields()[1], value);
      this.impressionTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'impressionTime' field has been set.
      * @return True if the 'impressionTime' field has been set, false otherwise.
      */
    public boolean hasImpressionTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'impressionTime' field.
      * @return This builder.
      */
    public com.vkc.avro.Impressions.Builder clearImpressionTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Impressions build() {
      try {
        Impressions record = new Impressions();
        record.adId = fieldSetFlags()[0] ? this.adId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.impressionTime = fieldSetFlags()[1] ? this.impressionTime : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Impressions>
    WRITER$ = (org.apache.avro.io.DatumWriter<Impressions>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Impressions>
    READER$ = (org.apache.avro.io.DatumReader<Impressions>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.adId);

    out.writeLong(this.impressionTime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.adId = in.readString(this.adId instanceof Utf8 ? (Utf8)this.adId : null);

      this.impressionTime = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.adId = in.readString(this.adId instanceof Utf8 ? (Utf8)this.adId : null);
          break;

        case 1:
          this.impressionTime = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










